version: "3.8"

services:
  banco:
    image: postgres:latest
    container_name: banco-profiles
    restart: always
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: ${DB_HOSTNAME}
    ports:
      - "5432:${DB_PORT}"
    networks:
      - profiles-network
    volumes:
      - postgresdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: oraculo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - banco
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - profiles-network

  profile:
    container_name: oraculo-profiles
    build: .
    restart: always
    depends_on:
      - banco
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    networks:
      - profiles-network
    links:
      - banco:${DB_HOST}
    ports:
      - "8000:${APP_PORT}"

volumes:
  node_modules:
  postgresdb:

networks:
  profiles-network:
    name: profiles-network
    driver: bridge
